### ISSUE TITLE
Atomic crashes when trying to use the SaltXMLImporter on a folder without a saltProject.salt file

### ISSUE THREAD

**Issue by arne-cl** [infraling/atomic#18]
I tried to open a *.salt file (describing an `SDocumentGraph`) that I had generated with SaltNPepper. I pointed the Pepper Module Import/SaltXMLImporter to the directory that contained the *.salt file. This is what happened:

``` java
Exception in thread "PepperModuleController[SaltXMLImporter]" de.hu_berlin.german.korpling.saltnpepper.salt.saltCommon.exceptions.SaltResourceNotFoundException: Cannot load Object, because the file '/home/arne/saltProject.salt' does not exist.
    at de.hu_berlin.german.korpling.saltnpepper.salt.impl.SaltFactoryImpl.load(SaltFactoryImpl.java:148)
    at de.hu_berlin.german.korpling.saltnpepper.salt.impl.SaltFactoryImpl.loadSCorpusGraph(SaltFactoryImpl.java:273)
    at de.hu_berlin.german.korpling.saltnpepper.salt.impl.SaltFactoryImpl.loadSCorpusGraph(SaltFactoryImpl.java:257)
    at de.hu_berlin.german.korpling.saltnpepper.salt.saltCommon.sCorpusStructure.impl.SCorpusGraphImpl.load(SCorpusGraphImpl.java:542)
    at de.hu_berlin.german.korpling.saltnpepper.pepperModules.saltXML.SaltXMLImporter.importCorpusStructure(SaltXMLImporter.java:66)
    at de.hu_berlin.german.korpling.saltnpepper.pepper.pepperFW.impl.PepperModuleControllerImpl.realImportCorpusStructure(PepperModuleControllerImpl.java:572)
    at de.hu_berlin.german.korpling.saltnpepper.pepper.pepperFW.impl.PepperModuleControllerImpl.run(PepperModuleControllerImpl.java:427)
    at java.lang.Thread.run(Thread.java:744)
```

Kind regards,
Arne

**Comment by sdruskat** [comment]
The SaltXMLImporter can only import full projects, including a `saltProject.salt` file, not single documents.
Closing this as `WONTFIX`.
