### ISSUE TITLE
Cannot load plugins from p2 repository.

### ISSUE THREAD

**Issue by lddubeau** [infraling/atomic#52]
### Versions

Atomic 0.2.0 (this is the latest stable release at time of writing)

```
$ java -version
openjdk version "1.8.0_72-internal"
OpenJDK Runtime Environment (build 1.8.0_72-internal-b05)
OpenJDK 64-Bit Server VM (build 25.72-b05, mixed mode)
```

This is running on Debian testing.

### Steps to reproduce

1. Unzip the Atomic package, cd into it.

2. `./atomic`

3. Select "Options > Install new plugins from p2 repository".

4. In the "Work with" field, select from the dropdown provided with the field the value "http://linktype.iaa.uni-jena.de/atomic/updates/".

### Expected results

Ideally, a list of plugins to install should show in the list under the "Work with" field.

If there is a problem, then a modal dialog should report the error. (Why modal? So that the user cannot miss it. A modal will prevent the user from doing anything else until the modal has been acknowledged.)

### Actual results

It shows "Pending..." and this is never replaced with a list of plugins.

The console shows:

```
[INFO ] 2015-12-01 09:40:25.906 [Worker-2] de.uni_jena.iaa.linktype.atomic.core.update.AtomicAutoUpdateJob: Can connect to linktype.iaa.uni-jena.de.
[INFO ] 2015-12-01 09:40:25.922 [Worker-2] de.uni_jena.iaa.linktype.atomic.core.update.P2Updater: Adding repository http://linktype.iaa.uni-jena.de/atomic/updates/
[ERROR] 2015-12-01 09:45:14.159 [Worker-2] de.uni_jena.iaa.linktype.atomic.core.update.P2Updater: Caught provisioning exception
java.lang.reflect.InvocationTargetException
        at de.uni_jena.iaa.linktype.atomic.core.update.P2Updater.addUpdateSite(P2Updater.java:79)
        at de.uni_jena.iaa.linktype.atomic.core.update.P2Updater.checkForUpdates(P2Updater.java:34)
        at de.uni_jena.iaa.linktype.atomic.core.update.AtomicAutoUpdateJob.run(AtomicAutoUpdateJob.java:49)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: org.eclipse.equinox.p2.core.ProvisionException: Unable to read repository at http://linktype.iaa.uni-jena.de/atomic/updates/content.xml.
        at org.eclipse.equinox.internal.p2.repository.CacheManager.createCache(CacheManager.java:189)
        at org.eclipse.equinox.internal.p2.metadata.repository.SimpleMetadataRepositoryFactory.getLocalFile(SimpleMetadataRepositoryFactory.java:66)
        at org.eclipse.equinox.internal.p2.metadata.repository.SimpleMetadataRepositoryFactory.load(SimpleMetadataRepositoryFactory.java:88)
        at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:57)
        at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:749)
        at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:651)
        at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:96)
        at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:92)
        at de.uni_jena.iaa.linktype.atomic.core.update.P2Updater.addUpdateSite(P2Updater.java:75)
        ... 3 more
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:209)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
        at org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:78)
        at org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:106)
        at org.apache.commons.httpclient.HttpConnection.readLine(HttpConnection.java:1116)
        at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.readLine(MultiThreadedHttpConnectionManager.java:1413)
        at org.apache.commons.httpclient.HttpMethodBase.readStatusLine(HttpMethodBase.java:1973)
        at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1735)
        at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1098)
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:346)
        at org.eclipse.ecf.provider.filetransfer.httpclient.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:227)
        at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:69)
        ... 1 more
```

There is a dialog that comes up that says "Problem Occurred" and has the following details:

```
Unable to read repository at http://linktype.iaa.uni-jena.de/atomic/updates/content.xml.
Connection reset
```

However, the dialog is not modal. Bringing Atomic into focus does not bring this dialog to the fore, and thus it can be easily missed. When the error dialog came up, I happened to be on a different workspace than where I started Atomic, and because of how I was shuffling between windows, the dialog was not visible to me, even when I switched back to Atomic. It was quite by chance that I found the dialog that reported the error.

**Comment by sdruskat** [comment]
Thanks for a well-written bug report!

The site at http://linktype.iaa.uni-jena.de/atomic/updates/ is indeed currently down, due to problems with the VM serving it. Critical Atomic infrastructure, such as the update site and documentation, will be moved to a more stable infrastructure in the next couple of days.

Re modality of the dialog: Atomic is directly using Eclipse functionality here, so it might not be easy to provide a modal dialog at this point. I'll investigate this nevertheless.
